spring:
  #http://localhost:8090/com/example/demo/v1/h2
  datasource:
    driverClassName: org.h2.Driver
    name: DEV_DEMO_DATA
    password: 
    url: jdbc:h2:mem:testdb;IGNORECASE=TRUE;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=Oracle
    username: sa
    schema: classpath:sql/create_schema.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath:sql/create_schema.sql #NOT WORK HERE
      mode: always
      platform: always