CREATE SCHEMA IF NOT EXISTS DEV_DEMO_DATA;
USE DEV_DEMO_DATA;
DROP TABLE IF EXISTS DEMO;
CREATE TABLE IF NOT EXISTS DEMO (
    ID INTEGER PRIMARY KEY,
    DEMO VARCHAR(255),
    DESC VARCHAR(255)
);
DROP TABLE IF EXISTS SUB_DEMO;
CREATE TABLE IF NOT EXISTS SUB_DEMO (
    ID INTEGER PRIMARY KEY,
    SUBDEMO VARCHAR(255),
    DESC VARCHAR(255)
);